[build]
  command = "make build"
  publish = "build/"

[[redirects]]
  from = "http://backend-dev.netlify.com/*"
  to = "https://backend.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://backend-dev.netlify.app/*"
  to = "https://backend.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://backend-dev.netlify.com/*"
  to = "https://backend.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://backend-dev.netlify.app/*"
  to = "https://backend.dev/:splat"
  status = 301
  force = true
